Update app-install.yml

diff --git a/.github/workflows/app-install.yml b/.github/workflows/app-install.yml
--- a/.github/workflows/app-install.yml
+++ b/.github/workflows/app-install.yml
@@ -67,11 +67,10 @@ jobs:
         run: |
           set +e  # Allow the command to fail
           echo "Running install script..."
-          EERROR_MSG=$(./${{ env.SCRIPT }} 2>&1 > /dev/null)  # Capture both stdout and stderr
-          echo "$ERROR_MSG" # Save error message to a file for later use
-          exit_code=$?  # Capture the exit code
+          EERROR_MSG=$(./${{ env.SCRIPT }} 2>&1 > /dev/null)  
+          echo "$ERROR_MSG" 
+          exit_code=$?  
           echo "exit_code=$exit_code"
-          echo "ERROR_MSG=$ERROR_MSG"
           echo "$ERROR_MSG" > result.log
           echo "exit_code=$exit_code" >> $GITHUB_ENV
           echo "ERROR_MSG=$ERROR_MSG" >> $GITHUB_ENV
