update .yml so it supports external repos

diff --git a/.github/workflows/script-test.yml b/.github/workflows/script-test.yml
--- a/.github/workflows/script-test.yml
+++ b/.github/workflows/script-test.yml
@@ -1,21 +1,23 @@
 name: Run Scripts on PVE Node for testing
+permissions:
+    pull-requests: write
 on:
-  pull_request:
+  pull_request_target:
     branches:
       - main
     paths:
-      - 'install/*.sh'
-      - 'ct/*.sh'
+      - 'install/**.sh'
+      - 'ct/**.sh'
 
 jobs:
   run-install-script:
-    runs-on: pvehost
+    runs-on: pvenode
     steps:          
       - name: Checkout PR branch (supports forks)
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.ref }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}  # Ensure it checks out the forked repo
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
           fetch-depth: 0          
           
       - name: Add Git safe directory
@@ -35,8 +37,7 @@ jobs:
           echo "Changed files: $CHANGED_FILES"
           echo "SCRIPT=$CHANGED_FILES" >> $GITHUB_ENV
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
 
       - name: Get scripts
         id: check-install-script
@@ -55,7 +56,7 @@ jobs:
           ALL_FILES=$(echo "${ALL_FILES[@]}" | xargs)
           echo "$ALL_FILES"
           echo "ALL_FILES=$ALL_FILES" >> $GITHUB_ENV
-        
+     
       - name: Run scripts
         id: run-install
         continue-on-error: true
@@ -69,7 +70,9 @@ jobs:
               CT_SCRIPT="ct/$STRIPPED_NAME.sh"
               if [[ ! -f $CT_SCRIPT ]]; then
                 echo "No CT script found for $STRIPPED_NAME"
-                exit 1
+                ERROR_MSG="No CT script found for $FILE"
+                echo "$ERROR_MSG" > result_$STRIPPED_NAME.log
+                continue
               fi
                 echo "Found CT script for $STRIPPED_NAME"
                 chmod +x "$CT_SCRIPT"
@@ -78,9 +81,10 @@ jobs:
               INSTALL_SCRIPT="install/$STRIPPED_NAME-install.sh"
               if [[ ! -f $INSTALL_SCRIPT ]]; then
                 echo "No install script found for $STRIPPED_NAME"
-                exit 1
-              fi
-                
+                ERROR_MSG="No install script found for $FILE"
+                echo "$ERROR_MSG" > result_$STRIPPED_NAME.log
+                continue
+              fi                
                 echo "Found install script for $STRIPPED_NAME"
                 chmod +x "$INSTALL_SCRIPT"
                 RUNNING_FILE=$FILE
@@ -115,8 +119,8 @@ jobs:
                 pct stop $container_id
                 pct destroy $container_id
             fi            
-          done
-      
+          done   
+
       - name: Post error comments
         run: |
           ERROR="false"
@@ -133,6 +137,7 @@ jobs:
               echo "Posting error message for $FILE"
               echo ${CLEANED_ERROR_MSG}
               gh pr comment ${{ github.event.pull_request.number }} \
+                --repo ${{ github.repository }} \
                 --body ":warning: The script _**$FILE**_ failed with the following message: <br> <div><strong>${CLEANED_ERROR_MSG}</strong></div>"
 
               
@@ -140,7 +145,9 @@ jobs:
             fi
           done
           echo "ERROR=$ERROR" >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Fail if error
         if: ${{ env.ERROR == 'true' }}
-        run: exit 1
+        run: exit 1 
