Add new workflow for script testing

diff --git a/.github/workflows/script-test.yml b/.github/workflows/script-test.yml
--- a/.github/workflows/script-test.yml
+++ b/.github/workflows/script-test.yml
@@ -135,8 +135,7 @@ jobs:
               ERROR="true"
             fi
           done
-          if [[ $ERROR == "true" ]]; then
-            exit 1
-          fi
-      
-  
+          echo "ERROR=$ERROR" >> $GITHUB_ENV
+      - name: Fail if error
+        if: ${{ env.ERROR }} == 'true'
+        run: exit 1 
